import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { query: { shop } } = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>GroupShop React App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
          {' '}
          Hi
          {' '}
          {shop}
        </h2>
        <h1 className={styles.title}>
          Welcome to
          {' '}
          <a href="/">Groupshop React App</a>
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          {' '}
          Groupshop.co
        </a>
      </footer>
    </div>
  );
};

export default Home;
