# This is a basic workflow to help you get started with Actions

name: GroupShop Frontend App
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - uses: actions/checkout@v3
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v3.0.0
      name: lint React App
      with:
        cmd: lint # will run `yarn run lint` command
    - uses: borales/actions-yarn@v3.0.0
      name: Build React App
      with:
        cmd: build # will run `yarn build` command
